<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="MensajesError.aspx.cs" Inherits="Cshop1._1.Formulario_web11" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    
     <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Contacto</title>

      <script  src="https://code.jquery.com/jquery-3.3.1.min.js"  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="  crossorigin="anonymous"></script>
      <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>



      <!-- fonts -->
      <link href="//fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">
      <link href="//fonts.googleapis.com/css?family=Muli:300,400" rel="stylesheet">
      <!-- /fonts -->
      <!-- css -->
      <link href="css/Estilos.css" rel='stylesheet' type='text/css' media="all" />
      <!-- /css -->
  </head>
  <body>
    <div id="contenidoMensaje" style="width:100%;">
        
        <h2 style="color:#000; border:thick; padding:10px;"><b>LISTA DE MENSAJES RECIBIDOS</b></h2>
    <div id="listaMensajes" style="margin-left:10%; width:80%; align-content:center;">
        
        <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="5" DataKeyNames="ID" DataSourceID="SqlDataSource1" ForeColor="Black" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID " InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                <asp:BoundField DataField="Nombre" HeaderText=" Nombre " SortExpression="Nombre" />
                <asp:BoundField DataField="Email" HeaderText=" Email " SortExpression="Email" />
                <asp:BoundField DataField="tipoConsulta" HeaderText="  Tipo de Consulta   " SortExpression="tipoConsulta" />
                <asp:BoundField DataField="Mensaje" HeaderText=" Mensaje " SortExpression="Mensaje" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
            <RowStyle BackColor="White"  />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:cshopConnectionString %>" SelectCommand="SELECT * FROM [mensajes]"></asp:SqlDataSource>
        <br />
    </div>

      </div> <!--FIN CONTENIDO MENSAJE-->
      </body>
</html>
</asp:Content>
